var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var schema = new Schema({
  // refer to the User model
  user: {type: Schema.Types.ObjectId, ref: 'User'},
  cart: {type: Object, required: true},
  address: {type: String, required: true},
  name: {type: String, required: true},
  // generated by Stripe.js
  paymentId: {type: String, required: true}
});

module.exports = mongoose.model('Order', schema);
